"""Profile the interim tables and write docs/DATA_PROFILE.md.

python -m ingest.profile [--interim data/interim] [--out docs/DATA_PROFILE.md]
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path

import pandas as pd

from ingest import paths

log = logging.getLogger(__name__)

# Draft columns worth tracking year by year (only those present are reported).
KEY_DRAFT_FIELDS = [
    "signing_bonus_usd",
    "pick_value",
    "person_birth_date",
    "school_name",
    "school_school_class",
    "school_state",
    "person_primary_position_abbreviation",
]
ROUND_BANDS = [(1, 5, "1-5"), (6, 10, "6-10"), (11, 20, "11-20"), (21, 999, "21+")]


def md_table(df: pd.DataFrame, index: bool = True) -> str:
    """Render a DataFrame as a GitHub Markdown table (no tabulate dependency)."""
    if index:
        df = df.reset_index()
    cols = [str(c) for c in df.columns]
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for row in df.itertuples(index=False):
        cells = ["" if pd.isna(v) else str(v) for v in row]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def pct(s: pd.Series) -> float:
    return round(100 * s.mean(), 1) if len(s) else float("nan")


def numeric_round(label: pd.Series) -> pd.Series:
    """'7' -> 7; supplemental labels like 'CB-A', '1C', 'PPI' -> NaN."""
    return pd.to_numeric(label, errors="coerce")


def round_band(label: pd.Series) -> pd.Series:
    rnd = numeric_round(label)
    band = pd.Series("supplemental", index=label.index, dtype="object")
    for lo, hi, name in ROUND_BANDS:
        band[rnd.between(lo, hi)] = name
    return band


def build_profile(interim: Path) -> str:
    picks = pd.read_parquet(interim / "draft_picks.parquet")
    people = pd.read_parquet(interim / "people.parquet")
    war_bat = pd.read_parquet(interim / "war_bat.parquet")
    war_pitch = pd.read_parquet(interim / "war_pitch.parquet")
    by_year = picks.groupby("draft_year")
    out: list[str] = ["# Data profile", ""]
    out.append(
        f"Generated by `make profile` from `data/interim/`. {len(picks):,} picks, "
        f"{picks['person_id'].nunique():,} unique people, draft years "
        f"{picks['draft_year'].min()}-{picks['draft_year'].max()}."
    )

    # 1. Picks and rounds per year
    rnd = numeric_round(picks["pick_round"])
    per_year = pd.DataFrame(
        {
            "picks": by_year.size(),
            "max_numeric_round": rnd.groupby(picks["draft_year"]).max().astype("Int64"),
            "supplemental_picks": rnd.isna().groupby(picks["draft_year"]).sum(),
        }
    )
    out += ["", "## Picks per year", "", md_table(per_year)]
    supp_labels = sorted(picks.loc[rnd.isna(), "pick_round"].dropna().unique())
    out += ["", f"Non-numeric round labels (supplemental rounds): `{', '.join(supp_labels)}`"]

    # 2. Column completeness
    overall = (picks.notna().mean() * 100).round(1).sort_values()
    out += ["", "## Draft column completeness (% non-null, all years)", ""]
    out.append(md_table(overall.rename("pct_non_null").rename_axis("column").to_frame()))

    key = [c for c in KEY_DRAFT_FIELDS if c in picks]
    yearly = (by_year[key].agg(lambda s: s.notna().mean()) * 100).round(1)
    out += ["", "## Key draft fields: % non-null by year", "", md_table(yearly)]
    if "pick_value" in picks:
        zeros = (picks["pick_value"].astype("string") == "0").groupby(picks["draft_year"])
        zero_pct = (zeros.mean() * 100).round(1)
        out += ["", '`pick_value` equal to the string `"0"` (% of picks), by year:', ""]
        out.append(md_table(zero_pct.rename("pct_zero").to_frame()))

    # 3. Bonus coverage by round band
    band = round_band(picks["pick_round"])
    bonus = (
        picks["signing_bonus_usd"]
        .notna()
        .groupby([picks["draft_year"], band])
        .mean()
        .mul(100)
        .round(1)
        .unstack()
    )
    band_order = [b for _, _, b in ROUND_BANDS] + ["supplemental"]
    bonus = bonus.reindex(columns=[b for b in band_order if b in bonus.columns])
    out += ["", "## Signing bonus coverage by round band (% non-null)", "", md_table(bonus)]
    out.append("")
    out.append("Blank cell = no picks in that band that year.")

    # 4. Categorical values
    out += ["", "## Categorical values", ""]
    for col in ("school_school_class", "person_primary_position_abbreviation"):
        if col in picks:
            counts = picks[col].value_counts(dropna=False).rename("picks").rename_axis(col)
            out += [f"### `{col}`", "", md_table(counts.to_frame()), ""]
    schools = picks["school_name"].dropna().drop_duplicates()
    sample = schools.sample(min(25, len(schools)), random_state=0).sort_values()
    out += [
        f"### Sample school names ({len(sample)} of {len(schools):,} distinct)",
        "",
        ", ".join(f"`{s}`" for s in sample),
    ]

    # 5. People coverage
    ppl = picks[["draft_year", "person_id"]].merge(
        people[["id", "birth_date", "mlb_debut_date"]],
        left_on="person_id",
        right_on="id",
        how="left",
    )
    grp = ppl.groupby("draft_year")
    people_cov = pd.DataFrame(
        {
            "picks": grp.size(),
            "pct_in_people": grp["id"].agg(lambda s: pct(s.notna())),
            "pct_birth_date": grp["birth_date"].agg(lambda s: pct(s.notna())),
            "pct_mlb_debut": grp["mlb_debut_date"].agg(lambda s: pct(s.notna())),
        }
    )
    out += ["", "## People: bio and debut coverage by draft year", "", md_table(people_cov)]

    # 6. WAR match
    war_ids = set(war_bat["mlb_ID"].dropna().astype(int)) | set(
        war_pitch["mlb_ID"].dropna().astype(int)
    )
    debuted = people[people["mlb_debut_date"].notna()]
    matched = debuted["id"].astype(int).isin(war_ids)
    last_war_season = int(max(war_bat["year_ID"].max(), war_pitch["year_ID"].max()))
    out += [
        "",
        "## WAR match",
        "",
        "Both Baseball-Reference tables have an MLBAM id column `mlb_ID` "
        f"(`war_bat`: {'yes' if 'mlb_ID' in war_bat else 'NO'}, "
        f"`war_pitch`: {'yes' if 'mlb_ID' in war_pitch else 'NO'}). "
        f"WAR seasons run through {last_war_season}.",
        "",
        f"Of {len(debuted):,} drafted people with an `mlbDebutDate`, "
        f"**{matched.sum():,} ({pct(matched)}%)** appear in WAR data by `mlb_ID`.",
    ]
    if (~matched).any():
        miss = debuted.loc[~matched, ["id", "full_name", "mlb_debut_date"]].head(10)
        out += ["", "Unmatched examples:", "", md_table(miss, index=False)]

    # 7. Repeat draftees
    times = picks.groupby("person_id")["draft_year"].agg(["count", list])
    repeats = times[times["count"] > 1]
    out += [
        "",
        "## Repeat draftees",
        "",
        f"**{len(repeats):,}** person ids appear in more than one draft row "
        f"({repeats['count'].sum():,} rows); max appearances = "
        f"{int(times['count'].max()) if len(times) else 0}.",
    ]
    if len(repeats):
        ex_ids = repeats.sort_values("count", ascending=False).index[:5]
        ex = picks[picks["person_id"].isin(ex_ids)].sort_values(["person_id", "draft_year"])
        cols = [
            c
            for c in (
                "person_id",
                "person_full_name",
                "draft_year",
                "pick_round",
                "pick_number",
                "team_name",
                "school_name",
                "school_school_class",
                "signing_bonus_usd",
            )
            if c in ex
        ]
        out += ["", md_table(ex[cols], index=False)]

    out += ["", "## Notes for Task 2", ""] + notes_for_task2(picks, people, per_year, repeats)
    return "\n".join(out) + "\n"


def notes_for_task2(
    picks: pd.DataFrame, people: pd.DataFrame, per_year: pd.DataFrame, repeats: pd.DataFrame
) -> list[str]:
    """Surprises worth designing around, computed so they stay true after re-pulls."""
    by_year = picks.groupby("draft_year")
    bonus_years = by_year["signing_bonus_usd"].agg(lambda s: s.notna().any())
    no_bonus = [int(y) for y, ok in bonus_years.items() if not ok]
    class_cov = by_year["school_school_class"].agg(lambda s: s.notna().mean())
    no_class = [int(y) for y, v in class_cov.items() if v < 0.5]

    joined = picks.merge(people, left_on="person_id", right_on="id", suffixes=("", "_p"))
    pos_same = pct(
        joined["person_primary_position_abbreviation"] == joined["primary_position_abbreviation"]
    )
    dy_mismatch = pct(picks["person_draft_year"] != picks["draft_year"])

    return [
        f"1. `signingBonus` is null for every pick in {no_bonus or 'no year'}; "
        "bonus analysis is effectively limited to the other years.",
        f"2. `school.schoolClass` (HS/4YR/JC level) is mostly null in {no_class or 'no year'}; "
        "school type must be inferred (e.g. from school name) for those years or left unknown.",
        "3. `schoolClass` mixes two encodings: `4YR JR`/`JC J2`/`HS SR` and bare `JR`/`SR`/`SO` "
        "(level missing). Needs a mapping table.",
        "4. `pickValue` (slot value) is a string, absent before 2017, partly present after, and "
        '`"0"` appears as a placeholder in some years; treat `0` as missing.',
        "5. Supplemental rounds use non-numeric labels (`CB-A`, `1C`, `PPI`, `SUP-2`, ...), so "
        "order by `pickNumber` (overall), not `pickRound`. Numeric rounds max out at "
        f"{per_year['max_numeric_round'].to_dict()}.",
        f"6. {len(repeats):,} people appear in more than one draft row. Task 2 must pick one "
        "row per person (e.g. last/signed draft) before computing outcome rates.",
        f"7. `person.draftYear` differs from the row's draft year on {dy_mismatch}% of picks, "
        "including people drafted only once in this window: it is a person-level field that can "
        "point to drafts outside 2012-2025. Ignore it; use `draft_year`.",
        f"8. Position in the draft payload matches the current `/people` position on {pos_same}% "
        "of rows, so it is likely the current position, not position at draft time.",
        "9. School names are not normalized (`TCU` vs `Texas Christian`, `LSU` vs "
        "`Louisiana State`), and `school_state` is empty for 2012-2016 (some names embed it, "
        "e.g. `(FL) HS`). Conference is not in the payload at all; it needs a school lookup.",
        "10. No draft date, only the year: age-at-draft needs a draft-date table (June through "
        "2020, July from 2021). WAR `mlb_ID` is float with nulls only on pre-1950 rows; cast to "
        "int after dropping nulls.",
    ]


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--interim", type=Path, default=paths.INTERIM)
    ap.add_argument("--out", type=Path, default=paths.DOCS / "DATA_PROFILE.md")
    args = ap.parse_args(argv)
    args.out.write_text(build_profile(args.interim))
    log.info("wrote %s", args.out)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    main()
